### ISSUE TITLE
Search should work for IDs

### ISSUE THREAD

**Issue by asishallab** [ScienceDb/admin_gui_gen#11]
`admin_gui_gen` AND `express_route_gen`: In the table view generated by template `views/pages/tableView.ejs` there is a search box within the filter bar. It connects to the route `get all <%- namePl %>` generated by `express_route_gen` template `views/pages/controller_get.ejs`. See the respective `helpers` in file `express_route_gen/helper.js`.

Extend the search functionality to accept IDs

**Comment by edwards33** [comment]
see '8 - Search should work for IDs' Branch for express_route_gen project

**Comment by edwards33** [comment]
see changes on 'export-selected-rows..' branch
