### ISSUE TITLE
Implement an extended search

### ISSUE THREAD

**Issue by asishallab** [ScienceDb/admin_gui_gen#12]
This issue affects `admin_gui_gen` AND `express_route_gen`. 
The implemented solution _MUST_ follow the design pattern of the already implemented search, but extend upon it.

So far the existing search only searches textual data model attributes with the SQL `like` operator and pre- and post-fixing the query with `%` as such: `%my_search_term%`.

The extended search should offer a selection of all "queryable" data model attributes and offer reasonable operators for them. This task needs careful design and planning. Please discuss your idea with Asis, before implementing.

**Comment by edwards33** [comment]
__Taking into account__: Please discuss your idea with Asis, before implementing.
Currently, extended search (as an example) is implemented for taxon route on ScienceDbBackend and ScienceDbGui (see: '9 - Implement an extended search' Branch for both projects)
