### ISSUE TITLE
Extend command line argument "belongsTos" to accept "name"

### ISSUE THREAD

**Issue by asishallab** [ScienceDb/admin_gui_gen#14]
In admin_gui_gen the command line argument `belongsTos` is used to define belongs-to-relationships (see [Sequelize Relationships](http://docs.sequelizejs.com/manual/tutorial/associations.html)). So far the argument "ModelName" is used to both specify the `target` as well as the attribute name in the `source` model, that holds the `foreign_key`. However, Sequelize offers the option of providing an `as: xyz` argument, e.g. 

````
User.belongsTo(UserRole, {as: 'role'});
````

Add an additional and optional argument to admin_gui_gen's `belongsTos` **JSON** that is named e.g. `as` and takes care of the above explained difference between `target` model name and the `source` attribute. This new `as` should hold the attribute, if that differs from the name of the `target` model class.

**Comment by edwards33** [comment]
Now FormElemns suport self reference (e.g. taxons have self-referencing fields). 'as' atribute gives the possibility to provide self-referencing fields for taxons.
see branch '4-Refactor-GUI-generation-command-functionality ' in admin_gui_gen project.
