### ISSUE TITLE
For each model only create a model_name_router.js file and do no longer modify the router/index.js

### ISSUE THREAD

**Issue by asishallab** [ScienceDb/admin_gui_gen#17]
Currently the [router/index.js file](github.com/ScienceDb/ScienceDbGui/blob/master/src/router/index.js) is modified to also contain the routes for a new model, every time `admin_gui_gen` is invoked. Change this behavior to only generate a file containing the imports and routes for the currently processed model and use that in ScienceDbGui to import the new routes. See [this ScienceDbGui Issue](https://github.com/ScienceDb/ScienceDbGui/issues/7) for further details.

**Comment by vsuaste** [comment]
For this part I created a new branch _routerFeature_ . 
Index router will bring together all routes for each model

**Comment by asishallab** [comment]
Merge routerFeature into master and close this Issue with the SHA commit, please.

**Comment by vsuaste** [comment]
Done. [#0873a1](https://github.com/ScienceDb/admin_gui_gen/commit/0873a1f6b808950e90d9153fc207719db4546d80)
[#546f8d](https://github.com/ScienceDb/admin_gui_gen/commit/546f8d69e0ed2851ad105ec06836b67498650316)
