### ISSUE TITLE
Switch from usage of command line arguments to a single JSON input file per model

### ISSUE THREAD

**Issue by asishallab** [ScienceDb/admin_gui_gen#18]
Currently `admin_gui_gen` is passed all input using command line arguments. Please refactor to the usage of JSON input files. Use a JSON structure _as close as possible_ to the input files used for [`express_graphql_model_gen`](https://github.com/ScienceDb/express_graphql_model_gen)

**Comment by vsuaste** [comment]
Now `admin_gui_gen` receives as input a folder containing a json file for each model.
The json file format is the same format used in the `express_graphql_model_gen`. (see [this issue]( https://github.com/ScienceDb/express_graphql_model_gen/issues/9) for more info)

**Comment by vsuaste** [comment]
QUESTION:

For the `belongTos` argument in the command line is necessary the following input info:
1. ModelName
2. foreignKey  
3. id
4. label
5. sublabel

My question is: The `id` argument (name of the primaryKey column in the target model) will be always _id_, right? Considering that in our first version of `express_graphql_model_gen` we decided that models will be linked only by theirs _id_ .

Also can you explain the difference between `label` and `sublabel`? I keep getting confuse about these. If you can give an example of use would be great

**Comment by asishallab** [comment]
#### Replying to above QUESTION 

You are correct: `id` will always be _literal_ "id" column. At the time of conception this was not yet clear.

`sublabel` can point to a different attribute than `label`. This will generate a more informative output in the Vue component that is used for selection. Example: Model User has attributes "name" and "email". Label could be "name" and sublabel could be "email". The possible selections shown to the user of the resulting single page application would be 
* John Doe
  * john.doe@gmail.com

I hope this clarifies things

**Comment by asishallab** [comment]
When done, please update the Readme accordingly with correct usage documentation.

**Comment by asishallab** [comment]
Please put in the commit SHA, if still findable. 
Close the Issue in any case, if truly done, please.

**Comment by vsuaste** [comment]
Done. [#c59670](https://github.com/ScienceDb/admin_gui_gen/commit/c596704eb6dd7dc6e4b1f5013c241d5b978c2eb3)
README [#ab590e](https://github.com/ScienceDb/admin_gui_gen/commit/ab590e4a440e058b0e0f7e930f7a0af5a7697fe2)
