### ISSUE TITLE
Refactor GUI generation command functionality in order to use Json objects for the attributes.

### ISSUE THREAD

**Issue by edwards33** [ScienceDb/admin_gui_gen#5]

**Comment by asishallab** [comment]
Low priority

**Comment by edwards33** [comment]
see: '4 - Refactor GUI generation command ... Json objects' Branch

**Comment by asishallab** [comment]
Missing adjustment of documentation. Please add proper and well understandable documentation to 

1. `admin_gui_gen/README.md`, and
2. The help function provided in file `admin_gui_gen/index.js`. See the original documentation generated when using the `-h` command line switch. Adjust this help message accordingly.

**Comment by edwards33** [comment]
Fixed: Missing adjustment of documentation
see: '4 - Refactor GUI generation command ... Json objects' Branch
