### ISSUE TITLE
Add functionality that automatically injects models components into routes array (which is located in ScienceDbGui/router folder)

### ISSUE THREAD

**Issue by edwards33** [ScienceDb/admin_gui_gen#6]

**Comment by asishallab** [comment]
admin_gui_gen (AGG) generates VueJs components and routes for the VueJs router in a target VueJs project. In this case the target project is `ScienceDbGui` (SDG). 

In the folder `router` of the target project (SDG) there is a file `index.js`. In this file the routes are defined. AGG generates new route files into the `router` directory. So far _only_ the `index.js` file is evaluated and the routes generated by AGG have to be copied _manually_ from the generated route file into the main `index.js`. 

Implement a method in the skeleton project `ScienceDbGui` `routes/index.js` to automatically execute (`eval`) all files in the same directory that match `*routes.js`. Goal is not to have to do the above manual copying of routes and imports defined in the generated files.

**Comment by edwards33** [comment]
see: '3 - Add functionality that automatically ...' Branch
